### ISSUE TITLE
Veeam PowerShell Telegraf

### ISSUE THREAD

**Issue by packtman** [jorgedlcruz/veeam_grafana#1]
Hi,

I would like to thank you for the hard work you have done here to make the Veeam-Grafana integration work. 

Can you please confirm on a few things:
a. Where is the powershell script placed? Inside the Veeam server or I can run it from any host powershell by setting BRHost = IP

b. Where is Telegraf installed in this scenario? Ideally my Telegraf, Influxdb and Grafana all are in one Linux box. 

c. If I have Telegraf installed in Linux box, how would I push the Veeam powershell generated data from the Veeam server to telegraf?

Thanks,
Dipen

**Comment by jorgedlcruz** [comment]
Hi packtman,
You're welcome!
a.- I have it on a edge machine, not on the Veeam Server, so, absolutely you can use the BRHost, you need to have installed Veeam Standalone console on that machine, and have an user/pass which can logins into the VBR Server, using Ad it's more easy.
b.- Well, I have one Linux box with InfluxDB, Grafana, the Telegraf agent needs to be installed on all machines you want to monitor, on this case on the Windows server on point a, but you can install the telegraf agent on the linux box to monitor that server, and so on.
c.- Telegraf is just the agent you need to install on your Windows machine on point a mentioned above. 

Maybe this image can helps
![alt text](https://www.jorgedelacruz.es/wp-content/uploads/2017/02/27/veeam-grafana-001.png "Diagram")

**Comment by packtman** [comment]
@jorgedlcruz Great!! Thanks for the quick response. Another issue I faced was to install VeeamPSSnapin in my host powershell. Can you suggest how would I install VeeamPSSnapin without using the script in Veeam Server (Veeam Server has preinstalled snapin)? 

I tried Get-PSSnapin VeeamPSSnapin or Add-PSSnapin VeeamPSSnapin. Also, your code which has the PSSnapin install command doesn't work for me :( 

Thanks

**Comment by jorgedlcruz** [comment]
Sure, follow this steps:
[https://www.jorgedelacruz.es/2017/02/16/veeam-instalando-veeam-standalone-console-gestion-remota-y-powershell-de-manera-sencilla/](https://www.jorgedelacruz.es/2017/02/16/veeam-instalando-veeam-standalone-console-gestion-remota-y-powershell-de-manera-sencilla/)

**Comment by packtman** [comment]
@jorgedlcruz this looks real good! I would try it and get back to you. 

Thanks
